[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.11.1"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_API_URL"

[[plugins]]
  package = "@netlify/plugin-nextjs"
